name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # - name: Navigate to frontend directory
    #   working-directory: ./frontend # Update this path to match your project's structure

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install
      working-directory: ./frontend # Add this line if your package.json is not in the root

    # - name: Run linting
    #   run: npm run lint
    #   working-directory: ./frontend

    - name: Run tests
      run: npm test
      working-directory: ./frontend

    - name: Build application
      run: npm run build
      working-directory: ./frontend

  # security:
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v3

  #   # - name: Navigate to frontend directory
  #   #   working-directory: ./frontend

  #   - name: Set up Node.js
  #     uses: actions/setup-node@v3
  #     with:
  #       node-version: '16'

  #   - name: Install dependencies
  #     run: npm install
  #     working-directory: ./frontend

  #   # - name: Run ESLint for Static Code Analysis
  #   #   run: npm run lint
  #   #   working-directory: ./frontend

  #   - name: Run Dependency Check with npm audit
  #     run: npm audit
  #     working-directory: ./frontend

  #   - name: Run SAST using NodeJsScan
  #     uses: a13xp0p0v/nodejsscan-action@v1
