name: Test Account and Payments Component

on: [push, pull_request]

jobs:
  test-account-payments:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run tests for Account and Payments component
      run: npm test -- AccountAndPayments.test.js
