name: CI/CD Pipeline - Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-integration:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install
      working-directory: ./frontend # Update this path if necessary

    - name: Run integration tests
      run: npm test -- Register.test.js
      working-directory: ./frontend

    - name: Build application
      run: npm run build
      working-directory: ./frontend
